# This Dockerfile is only for testing Dependabot same-tag digest refreshes.
FROM ghcr.io/jaysundu/testactions-dependabot-digest-fixture:1.0.0@sha256:ae9d7c5b1365614fb63316b23d36a5268de383ad32f6717c2bc1bfe1b12dc892
